databases:
  - name: fixu-db
    databaseName: fixu
    user: fixu_user
    plan: free

services:
  - type: web
    name: fixu-flask-app
    env: docker
    dockerfilePath: ./flask_app.Dockerfile
    envVars:
      - key: PORT
        value: "5000"
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FIXU_BOOTSTRAP_DB
        value: "1"
      - key: LARAVEL_ADMIN_URL
        value: "https://fixu-laravel-admin.onrender.com"

  - type: web
    name: fixu-laravel-admin
    env: docker
    dockerfilePath: ./laravel_admin.Dockerfile
    envVars:
      - key: PORT
        value: "80"
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false


  - type: web
    name: fixu-bridge-api
    env: docker
    dockerContext: ./bridge_api
    dockerfilePath: ./bridge_api.Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: INTERNAL_API_KEY
        generateValue: true
      - key: FLASK_APP_URL
        fromService:
          type: web
          name: fixu-flask-app
          property: host
      - key: LARAVEL_ADMIN_URL
        fromService:
          type: web
          name: fixu-laravel-admin
          property: host
