"""insert_admin_user

Revision ID: 88faf14a8b88
Revises: 0263e04a1a7f
Create Date: 2025-11-23 19:02:33.868578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88faf14a8b88'
down_revision = '0263e04a1a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO users (name, email, password_hash, role, created_at, updated_at)
        VALUES (
            'Admin',
            'admin@fixu.local',
            'pbkdf2:sha256:600000$uRPrxlTpGNwQ4XOU$3605de75e5a3304a93ba87c823367de1943643a3bec3a928ea80ffa4ad517443',
            'admin',
            NOW(),
            NOW()
        )
        ON CONFLICT (email) DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE email = 'admin@fixu.local'")
    # ### end Alembic commands ###
